on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: config/
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: list modules
        run: west list
      - name: West Build (SPC_EVDR Xiao SAMD)
        run: west build -s zmk/app -b seeeduino_xiao -d build/spc_evdr_xiao_samd -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DSHIELD=spc_evdr
      - name: West Build (SPC_EVDR Xiao BLE)
        run: west build -s zmk/app -b seeeduino_xiao_ble -d build/spc_evdr_xiao_ble -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DSHIELD=spc_evdr
      - name: SPC_EVDR .config
        if: ${{ always() }}
        run: cat -n build/spc_evdr_xiao_ble/zephyr/.config
      - name: Rename zmk.uf2
        run: |
          cp build/spc_evdr_xiao_samd/zephyr/zmk.uf2 spc_evdr_xiao_samd.uf2
          cp build/spc_evdr_xiao_ble/zephyr/zmk.uf2 spc_evdr_xiao_ble.uf2
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: '*.uf2'
      
